name: layout_tester
description: This helper package provides an easy interface for layout and widget composition testing. 
version: 0.1.0
homepage: https://github.com/ozML/layout_tester

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2

flutter:
  uses-material-design: true