name: layout_tester
description: Flutter layout testing utility
version: 0.0.1
homepage: https://github.com/ozML/layout_tester

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2

flutter:
  uses-material-design: true